### PR TITLE
Popup

### PR DESCRIPTION
**Pull request by akbarsazish**
I have created an arrays of object which makes dyanmic inejection of project section, while clicking on the seeproject button it finde the id of clicked project and show the details of that project on th modal (popup window).
I also used some css staff for design to look good the portfolio.

### CODE REVIEW

**Review by souad988 — CHANGES_REQUESTED** [review]
Hi @akbarsazish , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
Dynamic rendring implemented correctly
Equal collaboration 

## Required Changes ♻️
_Great work on implementing this modal popup work , one small issue improuve is the the image is taking more than it should do from the modal and we need to scroll to see the rest , if you can make take less width and make the popup cover a bit less width this will help reduce image size or opte for other solutions to make it look like the desing 
image (16)
image (17)

otherwise every thing seems good to me.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by akbarsazish** [comment]
Hello,
I hope you are doing well. I saw all the images that were in figma, the width of the photos is small. As you know, when we set the width and height of the photos to be smaller or larger than the original size, the shape of the photos changes completely. As requested by the previous Code Reviewer, I reduced the width of the modal, but this does not affect the photo. I will change the photo later, I want to post photos of the projects I have done before.  If you have a solution for them please let me know and I will consider it.
Thank

**Review by omarsalem7 — APPROVED** [review]
Hi @akbarsazish 😊, 
# STATUS: APPROVED! 🥇 💯 



Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by NatiG25 — COMMENTED** [review]
## :red_circle: INVALID PULL REQUEST :red_circle: 

## Hi @akbarsazish :wave:, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that's not for the 'Portfolio: validate contact form' milestone. Kindly, submit the correct PR. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request closed without merging**
